---

registry: registry.nordix.org
organization: cloud-native/meridio
tag: latest
pullPolicy: IfNotPresent

applicationName: target-a

configMapName: meridio-configuration

default:
  ambassadorSock: /var/lib/meridio/ambassador.sock
  trench:
    name: trench-a
  conduit:
    name: load-balancer
  stream:
    name: stream-a

tapa:
  image: tapa
  version: latest

ctraffic:
  image: ctraffic
  version: latest

nsp:
  targetPort: 7778
  serviceName: nsp-service

readinessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=unix://{{ .Values.default.ambassadorSock }}", "-connect-timeout=100ms", "-rpc-timeout=150ms"]
  initialDelaySeconds: 0

livenessProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=unix:///tmp/health.sock", "-connect-timeout=100ms", "-rpc-timeout=150ms"]
  initialDelaySeconds: 3
  timeoutSeconds: 3
  failureThreshold: 3

startupProbe:
  exec:
    command: ["/bin/grpc_health_probe", "-addr=unix:///tmp/health.sock", "-connect-timeout=100ms", "-rpc-timeout=150ms"]
  initialDelaySeconds: 0
  periodSeconds: 2
  timeoutSeconds: 2
  failureThreshold: 30

