---
# Source: meridio/templates/lb-fe.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-fe
  labels:
    app: lb-fe
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: lb-fe
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lb-fe
        "spiffe.io/spiffe-id": "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "lb-fe"
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image:  # to be filled by operator
          imagePullPolicy:  # Kubernetes default according to image tag
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args:  # to be filled by operator according to trench
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name: load-balancer
          image:  # to be filled by operator
          imagePullPolicy:  # Kubernetes default according to image tag
          startupProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=Readiness
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_SERVICE_NAME
              value:  # to be filled by operator
            - name: NSM_CONDUIT_NAME
              value:  # to be filled by operator
            - name: NSM_TRENCH_NAME
              value:  # to be filled by operator
            - name: NSM_NSP_SERVICE
              value:  # to be filled by operator
            - name: NSM_MAX_TOKEN_LIFETIME
              value: "10m"
            - name: NSM_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
            - name: tmp-lb
              mountPath: /tmp
              readOnly: false
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_ADMIN"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: nsc
          image:  # to be filled by operator if not specified
          imagePullPolicy:  # Kubernetes default according to image tag
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value:  # to be filled by operator
            - name: NSM_DIAL_TIMEOUT
              value: "30s"
            - name: NSM_REQUEST_TIMEOUT
              value: "300s"
            - name: NSM_MAX_TOKEN_LIFETIME
              value: "10m"
            - name: NSM_LOG_LEVEL
              value: "DEBUG"
            - name: NSM_LIVENESSCHECKENABLED
              value:  # to be filled by operator
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: fe
          image:  # to be filled by operator
          imagePullPolicy:  # Kubernetes default according to image tag
          startupProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=Readiness
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:  # will be filled by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=unix:///tmp/health.sock
                - -service=
                - -connect-timeout=250ms
                - -rpc-timeout=350ms
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NFE_NAMESPACE
              value:  # to be filled by operator
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "true"
            - name: NFE_EXTERNAL_INTERFACE
              value:  # to be filled by operator
            - name: NFE_NSP_SERVICE
              value:  # to be filled by operator
            - name: NFE_CONFIG_MAP_NAME
              value:  # to be filled by operator
            - name: NFE_TRENCH_NAME
              value:  # to be filled by operator
            - name: NFE_ATTRACTOR_NAME
              value:  # to be filled by operator
            - name: NFE_LOG_LEVEL
              value: "DEBUG"
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: tmp-fe
              mountPath: /tmp
              readOnly: false
            - name: run
              mountPath: /var/run/bird
              readOnly: false
            - name: etc
              mountPath: /etc/bird
              readOnly: false
            - name: log
              mountPath: /var/log
              readOnly: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
        - name: tmp-lb
          emptyDir:
            medium: Memory
        - name: tmp-fe
          emptyDir:
            medium: Memory
        - name: run
          emptyDir:
            medium: Memory
        - name: etc
          emptyDir:
            medium: Memory
        - name: log
          emptyDir:
            medium: Memory
