---
# Default values for nsm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tag: v1.5.0
pullPolicy: IfNotPresent

registry: ghcr.io
organization: networkservicemesh

forwarderVPPImage: cmd-forwarder-vpp
registryMemoryImage: cmd-registry-memory
nsmgrImage: cmd-nsmgr
excludePrefixesImage: cmd-exclude-prefixes-k8s
admissionWebhookImage: cmd-admission-webhook-k8s
nscImage: cmd-nsc
nscInitImage: cmd-nsc-init
