apiVersion: apps/v1
kind: Deployment
metadata:
  name: meridio-load-balancer
  labels:
    app: meridio-load-balancer
spec:
  selector:
    matchLabels:
      app: meridio-load-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: meridio-load-balancer
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
         { "name" : "meridio-$NAME",
           "namespace": "default",
           "interface": "nsm-1" }
        ]'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "meridio-load-balancer"
            topologyKey: kubernetes.io/hostname
      containers:
        - name: load-balancer
          image: registry.nordix.org/cloud-native/meridio/load-balancer:local
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_SERVICE_NAME
              value: load-balancer.$NAME.$NAME
            - name: NSM_CONDUIT_NAME
              value: load-balancer
            - name: NSM_TRENCH_NAME
              value: $NAME
            - name: NSM_NSP_SERVICE
              value: meridio-nsp-$NAME:7778
            - name: NO_START
              value: "no"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
        - name: fe
          image: registry.nordix.org/cloud-native/meridio/frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NFE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "false"
            - name: NFE_NSP_SERVICE
              value: meridio-nsp-$NAME:7778
            - name: NFE_CONFIG_MAP_NAME
              value: meridio-configuration-$NAME
            - name: NFE_TRENCH_NAME
              value: $NAME
            - name: NFE_ATTRACTOR_NAME
              value: "attractor1"
            - name: NFE_EXTERNAL_INTERFACE
              value: "nsm-1"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
